version: '3.9'

services:
  dhcp:
    build: .
    image: aisuhua/dhcp:latest
    container_name: dhcp
    command: "${INTERFACE}"
    restart: no
    network_mode: host
    ports:
      - 67:67/udp
    volumes:
      - ./data:/data 
