version: '3.9'

services:
  dhcp-server:
    build: .
    image: aisuhua/dhcp-server:latest
    command: "${INTERFACE}"
    restart: no
    network_mode: host
    ports:
      - 67:67/udp
    volumes:
      - ./data:/data 
